# Lab | Revisiting Machine Learning Case Study

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

--------------------------------------------------------------------------------------------------
In this lab, you will use learningSet.csv file which you already have cloned in today's activities.

-------------------------------------------------------------------------------------------------

In [2]:
#Importing necessary libraries
import pandas as pd
import numpy as np

In [3]:
# Loading the dataset into variable df
df = pd.read_csv("/content/drive/MyDrive/Ironhack/unit 7/7.01/learningSet.csv")

<ipython-input-3-16f0996e4f27>:2: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/drive/MyDrive/Ironhack/unit 7/7.01/learningSet.csv")

In [4]:
df.shape

(95412, 481)

### Instructions

--------------------------------------------------------------------------------------------------------
1. Complete the following steps on the categorical columns in the dataset:

- Check for null values in all the columns

- Exclude the following variables by looking at the definitions. Create a new empty list called drop_list. We will append this list and then drop all the columns in this list later:

    - OSOURCE - symbol definitions not provided, too many categories
    - ZIP CODE - we are including state already
    
----------------------------------------------------------------------------------------------------------

In [5]:
# Check for null values in each column
null_counts = df.isnull().sum()

# Display the count of null values per column
print(null_counts)

ODATEDW       0
OSOURCE       0
TCODE         0
STATE         0
ZIP           0
           ...
MDMAUD_R      0
MDMAUD_F      0
MDMAUD_A      0
CLUSTER2    132
GEOCODE2    132
Length: 481, dtype: int64

In [6]:
#Initializing an empty list to append the columns to drop
drop_list = []

In [7]:
# Append both column names to drop at once
drop_list.extend(['OSOURCE', 'ZIP'])

# Now, columns_to_drop contains the names of the columns you want to drop later
print(drop_list)

['OSOURCE', 'ZIP']

In [8]:
#Dropping the previous columns from our database
df_copy = df.copy()

df_copy = df_copy.drop(columns=drop_list)

df_copy

,ODATEDW,TCODE,STATE,MAILCODE,PVASTATE,DOB,NOEXCH,RECINHSE,RECP3,RECPGVG,...,TARGET_D,HPHONE_D,RFA_2R,RFA_2F,RFA_2A,MDMAUD_R,MDMAUD_F,MDMAUD_A,CLUSTER2,GEOCODE2
0,8901,0,IL,,,3712,0,,,,...,0.0,0,L,4,E,X,X,X,39.0,C
1,9401,1,CA,,,5202,0,,,,...,0.0,0,L,2,G,X,X,X,1.0,A
2,9001,1,NC,,,0,0,,,,...,0.0,1,L,4,E,X,X,X,60.0,C
3,8701,0,CA,,,2801,0,,,,...,0.0,1,L,4,E,X,X,X,41.0,C
4,8601,0,FL,,,2001,0,X,X,,...,0.0,1,L,2,F,X,X,X,26.0,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,9601,1,AK,,,0,0,,,,...,0.0,0,L,1,G,X,X,X,12.0,C
95408,9601,1,TX,,,5001,0,,,,...,0.0,1,L,1,F,X,X,X,2.0,A
95409,9501,1,MI,,,3801,0,,X,,...,0.0,1,L,3,E,X,X,X,34.0,B
95410,8601,0,CA,,,4005,0,X,,,...,18.0,1,L,4,F,X,X,X,11.0,A
95411,8801,2,NC,,,1801,0,X,,X,...,0.0,1,L,1,G,C,1,C,12.0,C

2. Identify columns that over 85% missing values

In [9]:
# Calculate the percentage of missing values for each column
missing_percentage = df_copy.isnull().sum() / len(df_copy) * 100

# Identify columns where the percentage of missing values is greater than 85%
missing_values_columns = missing_percentage[missing_percentage > 85].index.tolist()

# Print the list of column names with more than 85% missing values
print(missing_values_columns)

['NUMCHLD', 'RDATE_3', 'RDATE_4', 'RDATE_5', 'RDATE_6', 'RDATE_7', 'RDATE_10', 'RDATE_13', 'RDATE_15', 'RDATE_17', 'RDATE_20', 'RDATE_21', 'RDATE_23', 'RAMNT_3', 'RAMNT_4', 'RAMNT_5', 'RAMNT_6', 'RAMNT_7', 'RAMNT_10', 'RAMNT_13', 'RAMNT_15', 'RAMNT_17', 'RAMNT_20', 'RAMNT_21', 'RAMNT_23']

3. Remove those columns from the dataframe

In [10]:
# Removing the missing values columns from our dataframe
df_copy = df_copy.drop(columns=missing_values_columns)

df_copy

,ODATEDW,TCODE,STATE,MAILCODE,PVASTATE,DOB,NOEXCH,RECINHSE,RECP3,RECPGVG,...,TARGET_D,HPHONE_D,RFA_2R,RFA_2F,RFA_2A,MDMAUD_R,MDMAUD_F,MDMAUD_A,CLUSTER2,GEOCODE2
0,8901,0,IL,,,3712,0,,,,...,0.0,0,L,4,E,X,X,X,39.0,C
1,9401,1,CA,,,5202,0,,,,...,0.0,0,L,2,G,X,X,X,1.0,A
2,9001,1,NC,,,0,0,,,,...,0.0,1,L,4,E,X,X,X,60.0,C
3,8701,0,CA,,,2801,0,,,,...,0.0,1,L,4,E,X,X,X,41.0,C
4,8601,0,FL,,,2001,0,X,X,,...,0.0,1,L,2,F,X,X,X,26.0,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,9601,1,AK,,,0,0,,,,...,0.0,0,L,1,G,X,X,X,12.0,C
95408,9601,1,TX,,,5001,0,,,,...,0.0,1,L,1,F,X,X,X,2.0,A
95409,9501,1,MI,,,3801,0,,X,,...,0.0,1,L,3,E,X,X,X,34.0,B
95410,8601,0,CA,,,4005,0,X,,,...,18.0,1,L,4,F,X,X,X,11.0,A
95411,8801,2,NC,,,1801,0,X,,X,...,0.0,1,L,1,G,C,1,C,12.0,C

4. Reduce the number of categories in the column GENDER. The column should only have either "M" for males, "F" for females, and "other" for all the rest

  - Note that there are a few null values in the column. We will first replace those null values using the code below:

  print(categorical['GENDER'].value_counts())
  
  categorical['GENDER'] = categorical['GENDER'].fillna('F')

In [11]:
print(df_copy['GENDER'].value_counts())
df_copy['GENDER'] = df_copy['GENDER'].fillna('F')

F    51277
M    39094
      2957
U     1715
J      365
C        2
A        2
Name: GENDER, dtype: int64

In [12]:
# Replace values in 'gender' column where the value is not 'F' or 'M' with 'O'
df_copy.loc[~df['GENDER'].isin(['F', 'M']), 'GENDER'] = 'O'

print(df_copy['GENDER'].value_counts())

F    51277
M    39094
O     5041
Name: GENDER, dtype: int64

# Lab | Feature engineering

In this lab, you will use learningSet.csv file which you have already cloned in the previous activities.

### Instructions

Here we will work on cleaning some of the other columns in the dataset using the techniques that we used before in the lessons.

*   Check for null values in the numerical columns.
*   Use appropriate methods to clean the columns GEOCODE2, WEALTH1, ADI, DMA,and MSA.
*   Use appropriate EDA technique where ever necessary.

In [13]:
# Select columns with numerical data types
numerical_columns = df_copy.select_dtypes(include=['number']).columns.tolist()

# Print the list of numerical column names
print(numerical_columns)

['ODATEDW', 'TCODE', 'DOB', 'AGE', 'INCOME', 'WEALTH1', 'HIT', 'MBCRAFT', 'MBGARDEN', 'MBBOOKS', 'MBCOLECT', 'MAGFAML', 'MAGFEM', 'MAGMALE', 'PUBGARDN', 'PUBCULIN', 'PUBHLTH', 'PUBDOITY', 'PUBNEWFN', 'PUBPHOTO', 'PUBOPP', 'MALEMILI', 'MALEVET', 'VIETVETS', 'WWIIVETS', 'LOCALGOV', 'STATEGOV', 'FEDGOV', 'WEALTH2', 'POP901', 'POP902', 'POP903', 'POP90C1', 'POP90C2', 'POP90C3', 'POP90C4', 'POP90C5', 'ETH1', 'ETH2', 'ETH3', 'ETH4', 'ETH5', 'ETH6', 'ETH7', 'ETH8', 'ETH9', 'ETH10', 'ETH11', 'ETH12', 'ETH13', 'ETH14', 'ETH15', 'ETH16', 'AGE901', 'AGE902', 'AGE903', 'AGE904', 'AGE905', 'AGE906', 'AGE907', 'CHIL1', 'CHIL2', 'CHIL3', 'AGEC1', 'AGEC2', 'AGEC3', 'AGEC4', 'AGEC5', 'AGEC6', 'AGEC7', 'CHILC1', 'CHILC2', 'CHILC3', 'CHILC4', 'CHILC5', 'HHAGE1', 'HHAGE2', 'HHAGE3', 'HHN1', 'HHN2', 'HHN3', 'HHN4', 'HHN5', 'HHN6', 'MARR1', 'MARR2', 'MARR3', 'MARR4', 'HHP1', 'HHP2', 'DW1', 'DW2', 'DW3', 'DW4', 'DW5', 'DW6', 'DW7', 'DW8', 'DW9', 'HV1', 'HV2', 'HV3', 'HV4', 'HU1', 'HU2', 'HU3', 'HU4', 'HU5', 'HHD1', 'HHD2', 'HHD3', 'HHD4', 'HHD5', 'HHD6', 'HHD7', 'HHD8', 'HHD9', 'HHD10', 'HHD11', 'HHD12', 'ETHC1', 'ETHC2', 'ETHC3', 'ETHC4', 'ETHC5', 'ETHC6', 'HVP1', 'HVP2', 'HVP3', 'HVP4', 'HVP5', 'HVP6', 'HUR1', 'HUR2', 'RHP1', 'RHP2', 'RHP3', 'RHP4', 'HUPA1', 'HUPA2', 'HUPA3', 'HUPA4', 'HUPA5', 'HUPA6', 'HUPA7', 'RP1', 'RP2', 'RP3', 'RP4', 'MSA', 'ADI', 'DMA', 'IC1', 'IC2', 'IC3', 'IC4', 'IC5', 'IC6', 'IC7', 'IC8', 'IC9', 'IC10', 'IC11', 'IC12', 'IC13', 'IC14', 'IC15', 'IC16', 'IC17', 'IC18', 'IC19', 'IC20', 'IC21', 'IC22', 'IC23', 'HHAS1', 'HHAS2', 'HHAS3', 'HHAS4', 'MC1', 'MC2', 'MC3', 'TPE1', 'TPE2', 'TPE3', 'TPE4', 'TPE5', 'TPE6', 'TPE7', 'TPE8', 'TPE9', 'PEC1', 'PEC2', 'TPE10', 'TPE11', 'TPE12', 'TPE13', 'LFC1', 'LFC2', 'LFC3', 'LFC4', 'LFC5', 'LFC6', 'LFC7', 'LFC8', 'LFC9', 'LFC10', 'OCC1', 'OCC2', 'OCC3', 'OCC4', 'OCC5', 'OCC6', 'OCC7', 'OCC8', 'OCC9', 'OCC10', 'OCC11', 'OCC12', 'OCC13', 'EIC1', 'EIC2', 'EIC3', 'EIC4', 'EIC5', 'EIC6', 'EIC7', 'EIC8', 'EIC9', 'EIC10', 'EIC11', 'EIC12', 'EIC13', 'EIC14', 'EIC15', 'EIC16', 'OEDC1', 'OEDC2', 'OEDC3', 'OEDC4', 'OEDC5', 'OEDC6', 'OEDC7', 'EC1', 'EC2', 'EC3', 'EC4', 'EC5', 'EC6', 'EC7', 'EC8', 'SEC1', 'SEC2', 'SEC3', 'SEC4', 'SEC5', 'AFC1', 'AFC2', 'AFC3', 'AFC4', 'AFC5', 'AFC6', 'VC1', 'VC2', 'VC3', 'VC4', 'ANC1', 'ANC2', 'ANC3', 'ANC4', 'ANC5', 'ANC6', 'ANC7', 'ANC8', 'ANC9', 'ANC10', 'ANC11', 'ANC12', 'ANC13', 'ANC14', 'ANC15', 'POBC1', 'POBC2', 'LSC1', 'LSC2', 'LSC3', 'LSC4', 'VOC1', 'VOC2', 'VOC3', 'HC1', 'HC2', 'HC3', 'HC4', 'HC5', 'HC6', 'HC7', 'HC8', 'HC9', 'HC10', 'HC11', 'HC12', 'HC13', 'HC14', 'HC15', 'HC16', 'HC17', 'HC18', 'HC19', 'HC20', 'HC21', 'MHUC1', 'MHUC2', 'AC1', 'AC2', 'ADATE_2', 'ADATE_3', 'ADATE_4', 'ADATE_5', 'ADATE_6', 'ADATE_7', 'ADATE_8', 'ADATE_9', 'ADATE_10', 'ADATE_11', 'ADATE_12', 'ADATE_13', 'ADATE_14', 'ADATE_15', 'ADATE_16', 'ADATE_17', 'ADATE_18', 'ADATE_19', 'ADATE_20', 'ADATE_21', 'ADATE_22', 'ADATE_23', 'ADATE_24', 'CARDPROM', 'MAXADATE', 'NUMPROM', 'CARDPM12', 'NUMPRM12', 'RDATE_8', 'RDATE_9', 'RDATE_11', 'RDATE_12', 'RDATE_14', 'RDATE_16', 'RDATE_18', 'RDATE_19', 'RDATE_22', 'RDATE_24', 'RAMNT_8', 'RAMNT_9', 'RAMNT_11', 'RAMNT_12', 'RAMNT_14', 'RAMNT_16', 'RAMNT_18', 'RAMNT_19', 'RAMNT_22', 'RAMNT_24', 'RAMNTALL', 'NGIFTALL', 'CARDGIFT', 'MINRAMNT', 'MINRDATE', 'MAXRAMNT', 'MAXRDATE', 'LASTGIFT', 'LASTDATE', 'FISTDATE', 'NEXTDATE', 'TIMELAG', 'AVGGIFT', 'CONTROLN', 'TARGET_B', 'TARGET_D', 'HPHONE_D', 'RFA_2F', 'CLUSTER2']

In [17]:
#Check for nulls
df_copy[numerical_columns].isnull().sum()

ODATEDW         0
TCODE           0
DOB             0
AGE         23665
INCOME      21286
            ...
TARGET_B        0
TARGET_D        0
HPHONE_D        0
RFA_2F          0
CLUSTER2      132
Length: 382, dtype: int64

In [16]:
#Display column GEOCODE2 unique values
df_copy["GEOCODE2"].value_counts()

A    34484
B    28505
D    16580
C    15524
       187
Name: GEOCODE2, dtype: int64

In [18]:
#Checking for nulls
df_copy["GEOCODE2"].isnull().sum()

132

In [19]:
# Replace null values in 'GEOCODE2' with 'O'
df_copy['GEOCODE2'] = df['GEOCODE2'].fillna('O')

In [20]:
#Display column GEOCODE2 unique values
df_copy["GEOCODE2"].value_counts()

A    34484
B    28505
D    16580
C    15524
       187
O      132
Name: GEOCODE2, dtype: int64

In [22]:
# Specify the column name you're interested in
column_name = 'GEOCODE2'

# Count the number of rows where the specified column is equal to ' '
rows_with_space = (df_copy["GEOCODE2"] == ' ').sum()

# Print the result
print(f"Number of rows where '{column_name}' is equal to a space: {rows_with_space}")

Number of rows where 'GEOCODE2' is equal to a space: 187

In [24]:
# Replace values in the specified column equal to ' ' with 'O'
df_copy["GEOCODE2"].replace(' ', 'O', inplace=True)

#Display column GEOCODE2 unique values
df_copy["GEOCODE2"].value_counts()

A    34484
B    28505
D    16580
C    15524
O      319
Name: GEOCODE2, dtype: int64

In [25]:
#Display column WEALTH1 unique values
df_copy["WEALTH1"].value_counts()

9.0    7585
8.0    6793
7.0    6198
6.0    5825
5.0    5280
4.0    4810
3.0    4237
2.0    4085
1.0    3454
0.0    2413
Name: WEALTH1, dtype: int64

In [30]:
# Convert the column from float to int
df_copy["WEALTH1"] = df_copy["WEALTH1"].fillna(0).astype(int)

In [33]:
#Display column GEOCODE2 unique values
df_copy["WEALTH1"].value_counts()

0    47145
9     7585
8     6793
7     6198
6     5825
5     5280
4     4810
3     4237
2     4085
1     3454
Name: WEALTH1, dtype: int64

In [34]:
#Display column ADI unique values
df_copy["ADI"].value_counts()

13.0     7296
51.0     4622
65.0     3765
57.0     2836
105.0    2617
         ...
651.0       1
103.0       1
601.0       1
161.0       1
147.0       1
Name: ADI, Length: 204, dtype: int64

In [35]:
# Convert the column from float to int
df_copy["ADI"] = df_copy["ADI"].fillna(0).astype(int)

#Display column ADI unique values
df_copy["ADI"].value_counts()

13     7296
51     4622
65     3765
57     2836
105    2617
       ...
651       1
103       1
601       1
161       1
147       1
Name: ADI, Length: 204, dtype: int64

In [36]:
#Display column DMA unique values
df_copy["DMA"].value_counts()

803.0    7296
602.0    4632
807.0    3765
505.0    2839
819.0    2588
         ...
569.0       1
554.0       1
584.0       1
552.0       1
516.0       1
Name: DMA, Length: 206, dtype: int64

In [37]:
# Convert the column from float to int
df_copy["DMA"] = df_copy["DMA"].fillna(0).astype(int)

#Display column ADI unique values
df_copy["DMA"].value_counts()

803    7296
602    4632
807    3765
505    2839
819    2588
       ...
569       1
554       1
584       1
552       1
516       1
Name: DMA, Length: 206, dtype: int64

In [38]:
#Display column MSA unique values
df_copy["MSA"].value_counts()

0.0       21333
4480.0     4606
1600.0     4059
2160.0     2586
520.0      1685
          ...
9140.0        1
3200.0        1
9280.0        1
743.0         1
8480.0        1
Name: MSA, Length: 298, dtype: int64

In [39]:
# Convert the column from float to int
df_copy["MSA"] = df_copy["MSA"].fillna(0).astype(int)

#Display column ADI unique values
df_copy["MSA"].value_counts()

0       21465
4480     4606
1600     4059
2160     2586
520      1685
        ...
9140        1
3200        1
9280        1
743         1
8480        1
Name: MSA, Length: 298, dtype: int64